logger: {
  file: logs/gomodule.log,
  level: debug,
  formatter: text, # text or json
  format: '2006-01-02 15:04:05',
  console: true,
  reportcaller: false,
}

SimpleModule: {
  Test: 'hello world'
}

